### ISSUE TITLE
Notation for missingness is confusing

### ISSUE THREAD

**Issue by jgabry** [paul-buerkner/non-factorized-loo#1]
As I'm making edits I noticed something that's not wrong but I think will be confusing to readers. 

The notation y_mis is used for a parameter corresponding to a _single_ missing observation, while y_mis(i) is used for the entire set of observations y except containing y_mis instead of y_i. It seems unnecessarily confusing not to use "i" when referring to the single observation/parameter and to use it instead in the name for the vector. One option would be just to flip it, but then the notation for the vector wouldn't indicate that only the ith entry is different. Another option would be to use bold for vectors throughout, and then if the y is y_mis(i) were bold it wouldn't be so weird that it's not only referring to the ith of something. What do you guys think?

**Comment by paul-buerkner** [comment]
Flipping it around would probably be the easiest option even though still suboptimal. I don't like the bold notation since it costs so much effort to do it consistently and usually is not required to understand the text.

**Comment by paul-buerkner** [comment]
And thanks for all the updates you already made!!

**Comment by jgabry** [comment]
Yeah I don’t have a great solution for the notation. In theory I like the bold idea but in practice I totally agree with your objections to it. I guess we flip it for now and then if anyone has a better idea we can always change it. Since I’m still editing I can make the change when I push the next bunch. 

(And I got the git issue sorted out. I needed to log out and log back in for some reason and then it recognized me as having permissions)

**Comment by jgabry** [comment]
How about keeping y_mis(i) for the vector and using y_i^mis for the parameter? It's still a bit confusing but maybe better than before? So for example, the expression for y_mis(i) would then be:

![image](https://user-images.githubusercontent.com/7796803/39020634-9a653eca-43fb-11e8-9c68-bae1debd1c53.png)

Or is that worse?

**Comment by paul-buerkner** [comment]
i like that one.

Jonah Gabry <notifications@github.com> schrieb am Fr., 20. Apr. 2018, 00:01:

**Comment by jgabry** [comment]
Ok I changed it to that in my latest commits.
